---
dependency:
  name: galaxy
driver:
  name: docker
  options:
    # options relevant if started with molecule
    # `create -d delegated` to apply locally
    managed: false
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: instance
    image: docker-ubuntu2404-ansible:latest
    command: ""
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    cgroupns_mode: host
    privileged: true
provisioner:
  name: ansible
  log: true
  inventory:
    host_vars:
      instance:
        ansible_user: ansible
verifier:
  name: ansible
