---
dependency:
  name: galaxy
driver:
  name: docker
  options:
    # options relevant if started with molecule `create -d delegated` to apply locally
    managed: False
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: instance
    image: "docker-${MOLECULE_DISTRO:-ubuntu2024}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    cgroupns_mode: host
    privileged: True
provisioner:
  name: ansible
  log: True
  inventory:
    host_vars:
      instance:
        ansible_user: ansible
verifier:
  name: ansible
